### ISSUE TITLE
Add to Play Store

### ISSUE THREAD

**Issue by Penknife0915** [jamal2362/URL-Radio#59]
Adding it to the Play Store would offer users a convenient and secure way to access the app.

**Comment by jamal2362** [comment]
This app was until a few months ago in the Google Play Store. But I removed it because the guidelines are getting stricter. e.g. Android Auto and much more.

Unfortunately, this app will never appear again for the Google Play Store.

If I would publish this app there again, is to be expected with large restrictions.

This project is a hobby and I do it on the side, so I don't care if it is in the Play Store or not.
