### ISSUE TITLE
bug: restored stations are not rendered

### ISSUE THREAD

**Issue by itsmartashub** [jamal2362/URL-Radio#65]
After the latest update (`10.9`) I cannot restore the stations backup. I mean, the backup has been restored because when I downgrade to `10.8` the stations are visible, but in `10.9` they are not rendered for some reason.

(I have tried and with cleared app storage before restore)

Phone: `Poco F3`
OS: `Android 13`
ROM: `MIUI 14.0.7.0`

**Comment by monstorix** [comment]
It might be caused by the newly-added bitrate and codec information display, the backup json file from old versions didn't have those new infos. The station entries backed to normal after I tried adding the bitrate and codec info manually in my backup json file.

**Comment by itsmartashub** [comment]
Hm, so other than manually updating the `json` file, what is the solution?

Could you perhaps make an update where you verify if the current property of the json object exists before rendering/using it (if you loop through each)?

I mean, I can manually re-add all stations and create a new backup in `v10.9` with these new values, but, in the future, if you add additional features regarding what to keep, this could be an issue with every newly added `json` property.

**Comment by jamal2362** [comment]
Due to the new structure of the JSON as codec and bitrate have been added, it may happen that the stations cannot be restored.

For me it was enough to restore the stations, after restoring the stations the codec and bitrate are automatically added in the JSON.

For example, a friend of mine did not have to restore anything from 10.8 to 10.9.
He had more luck.

Those where nothing can restore the stations, I'm sorry but then you have to add the radio stations again, from new.

In the near future, nothing more is planned what comes new into the JSON file.

With a little effort, however, you can still restore the stations.

Open the collection.json in the ZIP file and add the codec and bitrate for each station.

I close this thread, but you can still write here.

**Comment by jamal2362** [comment]
@itsmartashub 

If you want then send me the backup of the stations from the 10.8.

I will be happy to take a look at it.

**Comment by itsmartashub** [comment]
Nothing new is planned to be added to backup `json` in the future? So tagging/categorizing/grouping stations is not on the "roadmap"? 😢

Thank you, I appreciate the time you are willing to allocate. I've already re-added stations, but if you need it for some debugging things, or to be sure that leaking these new properties cause the render bug, I'll send, just tell me where could I ping you.
